### PR TITLE
Fix @Store concurrency

### LINKED ISSUE #38: @Store violates concurrency rules
## Checklist

- [x] I updated to the latest version and the problem persists.
- [ ] I searched the [existing GitHub issues][1] and this hasn't already been reported. -- This was mentioned in #35, but this is a separate issue.

## Overview

While `ObservedObject` is not *completely* `@MainActor`, its wrapped value is. When using the property wrapper syntax, as is written now:
```swift
@ObservedObject internal var observableObject: ErasedObservableObject
```
the entire thing is implicitly `@MainActor`. However, the `update` method (which references `_observableObject`) is not guaranteed to be called on any specific actor.

The solution is to desugar the property wrapper:
```swift
fileprivate var _observableObject: ObservedObject<ErasedObservableObject>

@MainActor internal var observableObject: ErasedObservableObject {
    return _observableObject.wrappedValue
}
```

## Example Reproduction

N/A, just compile the library with the `-warn-concurrency` flag

## Behavior

Ideally, no warnings should arise when the `-warn-concurrency` flag is set.

## Environment

| Software    | Version |
|:------------|:--------|
| macOS       | `12.6.0` |
| Xcode       | `14.0.1` |
| Dependiject | `0.2.0` |

[1]: https://github.com/Tiny-Home-Consulting/Dependiject/issues?q=is%3Aissue

### PR DESCRIPTION
**Pull request by bbrk24**
## Issue Link

Fixes #38

## Overview of Changes

This PR makes a slight adjustment to the `@Store` property wrapper to follow Swift's concurrency rules. However, this also requires Swift 5.5 or later, so both the code and documentation have been updated accordingly.

### Anything you want to highlight?

While the `nonisolated` keyword isn't strictly required, adding that with no other changes upgrades this problem from an opt-in warning to a guaranteed error.

I didn't enable the `-warn-concurrency` flag because it warns about accesses to `Factory.options`. ~~However, I left it commented-out in Package.swift, so you can easily un-comment it to enable the warning.~~

Edit: I will remove the comment from Package.swift. To enable the flag, add the following lines to the target:

```diff
         .target(
             name: "Dependiject",
             path: "Dependiject",
+            swiftSettings: [
+                .unsafeFlags([
+                    "-warn-concurrency"
+                ])
+            ],
             linkerSettings: [
                 .linkedFramework("SwiftUI"),
                 .linkedFramework("Combine")
             ]
         ),
```

## Test Plan

Enable the `-warn-concurrency` compiler flag. The Store should emit no warnings.

### CODE REVIEW

File: Package.swift [hunk 1]
```diff
@@ -25,6 +25,11 @@ let package = Package(
         .target(
             name: "Dependiject",
             path: "Dependiject",
+//            swiftSettings: [
+//                .unsafeFlags([
+//                    "-warn-concurrency"
+//                ])
+//            ],
```
Comment (Ljgleeson) [inline Package.swift:32]: Would we ever want to enable the warning about accesses to Factory.options? I'm just thinking if not then we can just remove this but if we decide to keep this it might be good to add a mention of it in the change log (i.e., "added optional warning in the Package file that can be uncommented if user wants warnings about accesses to Factory.options")

Comment (bbrk24) [reply Package.swift:32]: No, honestly I'll probably remove this in a later commit to this branch. I included it to demonstrate how to enable the warning. This could've gone in the PR description instead.

File: CHANGELOG.md [hunk 2]
```diff
@@ -3,6 +3,16 @@
 All notable changes to this project will be documented in this file. See [Keep a Changelog] for
 formatting guidelines.
 
+## Unreleased
+
+### Breaking
```
[the remark this answers is not in the document]
Comment (Ljgleeson) [reply CHANGELOG.md:8]: Okay yeah that makes sense

File: Package.swift (hunk 1 above)
Comment (Ljgleeson) [reply Package.swift:32]: Okay, once its removed then I'll approve this pr because besides that it all looked good to me

**Review by Ljgleeson — APPROVED** [review]

File: CHANGELOG.md (hunk 2 above)
[the remark this answers is not in the document]
Comment (bbrk24) [reply CHANGELOG.md:8]: As per Wesley's comment on #45, this will be reworded and not under a `Breaking` heading.

File: iOS 13 Example/Dependiject.xcodeproj/project.pbxproj [hunk 3]
```diff
@@ -355,15 +354,12 @@
...
-				"${BUILT_PRODUCTS_DIR}/MockingbirdFramework/Mockingbird.framework",
+			inputFileListPaths = (
+				"${PODS_ROOT}/Target Support Files/Pods-Dependiject_Tests/Pods-Dependiject_Tests-frameworks-${CONFIGURATION}-input-files.xcfilelist",
 			);
 			name = "[CP] Embed Pods Frameworks";
-			outputPaths = (
-				"${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/Dependiject.framework",
-				"${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/Mockingbird.framework",
+			outputFileListPaths = (
+				"${PODS_ROOT}/Target Support Files/Pods-Dependiject_Tests/Pods-Dependiject_Tests-frameworks-${CONFIGURATION}-output-files.xcfilelist",
```
Comment (wboyd600) [inline iOS 13 Example/Dependiject.xcodeproj/project.pbxproj:362]: Are these just xcode generated changes due to the requirements update?

**Review by wboyd600 — COMMENTED** [review]
It definitely gets rid of the warnings when you up the swift concurrency checking to complete in the example projects. I was wondering why only the project.pbxproj file changed for the iOS 13 example project.

not related to this PR but I noticed this warning when running the documentation locally:
>     Building targets in manual order is deprecated - check "Parallelize build for command-line builds" in the project editor, or set DISABLE_MANUAL_TARGET_ORDER_BUILD_WARNING in any of the targets in the current build to suppress this warning

File: iOS 13 Example/Dependiject.xcodeproj/project.pbxproj (hunk 3 above)
Comment (bbrk24) [reply iOS 13 Example/Dependiject.xcodeproj/project.pbxproj:362]: As far as I'm aware, yes, that's exactly why.

**Comment by bbrk24** [comment]
> I was wondering why only the project.pbxproj file changed for the iOS 13 example project.

@wboyd600 The iOS 14 example was already in the Xcode 13 format, last I checked. I updated it for the iOS 13 example to reflect the fact that we're requiring Xcode 13 anyways.

**Review by wboyd600 — APPROVED** [review]
