### PR TITLE
Make Factory thread-safe using NSRecursiveLock

### LINKED ISSUE #35: Factory is not thread safe
## Checklist

- [x] I updated to the latest version and the problem persists.
- [x] I searched the [existing GitHub issues][1] and this hasn't already been reported.

## Overview

The Factory's methods are not thread-safe. Calling `register(builder:)` or `resolve(_:name:)` from multiple threads at once often results in crashes.

## Example Reproduction

```swift
await withTaskGroup(of: Void.self) { group in
    for i in 0..<100 {
        group.addTask {
            Factory.register {
                Service(.singleton, Int.self) { [i] (_) in i }
            }
        }
    }
}

await withTaskGroup(of: Void.self) { group in
    for _ in 0..<100 {
        group.addTask {
            _ = Factory.shared.resolve(Int.self)
        }
    }
}
```

## Behavior

The above code will often crash with a fatal error, EXC_BAD_ACCESS, or arithmetic error, but not always.

Either the Factory's methods should be documented as not thread-safe, or they should be enforced to always run on the same thread (e.g. `@MainActor`).

## Environment

| Software    | Version |
|:------------|:--------|
| macOS       | `12.6.0` |
| Xcode       | `14.0.1` |
| Dependiject | `0.2.0` |

[1]: https://github.com/Tiny-Home-Consulting/Dependiject/issues?q=is%3Aissue

### PR DESCRIPTION
**Pull request by bbrk24**
## Issue Link

Fixes #35 

## Overview of Changes

This PR protects the methods of `Factory` with an `NSRecursiveLock`. This ensures that it can safely be called from any thread.

### Anything you want to highlight?

This PR is meant as a more user-friendly and both backwards- and forwards-compatible alternative to #36. As it turns out, Swift concurrency is not required to solve the problem.

## Test Plan

Try to call `Factory.register` and `Factory.shared.resolve` in various ways in concurrent contexts. I was unable to get it to break.

### CODE REVIEW

File: Dependiject/Factory.swift [hunk 1]
```diff
@@ -135,9 +145,14 @@ public class Factory: Resolver {
         }
         
         resolutionDepth += 1
+        defer {
+            resolutionDepth -= 1
+        }
```
Comment (Ljgleeson) [inline Dependiject/Factory.swift:150]: Do we need two separate defers in this function? Couldn't we add `lock.unlock()` underneath the decrementing of resolutionDepth in this one defer?

Comment (bbrk24) [reply Dependiject/Factory.swift:150]: The main purpose of `defer` is for visual grouping. Strictly speaking, we could move both of these to the very bottom of the function, but it's more legible and less error-prone to group `defer { close() }`-type calls with their corresponding `open()`s.

Also worth note, defers are called in the reverse order they're constructed, so this is decremented *before* the lock is unlocked.

Comment (Ljgleeson) [reply Dependiject/Factory.swift:150]: I mean I would say that that isn't `defers` main purpose but rather a benefit of using them but never the less, I didn't know they are called in the reverse order of their construction but now I see that this format makes sense.

**Review by Ljgleeson — APPROVED** [review]

File: Tests/ParallelResolutionTest.swift [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+    
+    func test_parallelResolutions() {
+        Factory.register {
+            // test both of the stateful registration types
+            Service(.singleton, Int.self) { _ in 1 }
+            Service(.weak, C.self) { _ in C() }
+        }
+        
+        DispatchQueue.concurrentPerform(iterations: 1000) { _ in
+            _ = Factory.shared.resolve(C.self)
```
Comment (wboyd600) [inline Tests/ParallelResolutionTest.swift:29]: this passes by not crashing right?

File: Dependiject/Factory.swift [hunk 3]
```diff
@@ -73,7 +75,8 @@ internal func enforceCondition(
 }
 
 /// The class to which you register dependencies.
-public class Factory: Resolver {
+public final class Factory: Resolver {
+    private let lock = NSRecursiveLock()
     private var registrations: [Registration] = []
     private var resolutionDepth: UInt = 0
```
Comment (wboyd600) [inline Dependiject/Factory.swift:81]: Was there an issue with locking these? I think I remember you mentioning that

File: Dependiject/Factory.swift [hunk 4]
```diff
@@ -160,3 +172,9 @@ public class Factory: Resolver {
         }
     }
 }
+
+#if swift(>=5.5)
+extension Factory: @unchecked Sendable {
+}
+#endif
+
```
Comment (wboyd600) [inline Dependiject/Factory.swift:180]: What's this for? because it's a class it can't implicitly conform to Sendable? So basically, if you're using swift 5.5 or greater you can use the Factory in an async context?

File: Tests/ParallelResolutionTest.swift (hunk 2 above)
Comment (bbrk24) [reply Tests/ParallelResolutionTest.swift:29]: Correct. On master this test will (usually) crash.

File: Dependiject/Factory.swift (hunk 3 above)
Comment (bbrk24) [reply Dependiject/Factory.swift:81]: The original `@Locked` property wrapper I wrote had the problem that a mutation would lock once for the get and once for the set, rather than keeping the lock throughout the entire mutation. This does nothing to prevent data races.

File: Dependiject/Factory.swift (hunk 4 above)
Comment (bbrk24) [reply Dependiject/Factory.swift:180]: > because it's a class it can't implicitly conform to Sendable?

Correct, only actors implicitly conform to Sendable. The original proposal had structs and enums also being implicitly Sendable, but that's not the behavior I've seen in Swift 5.7.

> So basically, if you're using swift 5.5 or greater you can use the Factory in an async context?

Correct. Swift 5.4 doesn't know about `Sendable` or `@unchecked`, so this had to be hidden behind a compiler version check.

File: Dependiject/Factory.swift (hunk 3 above)
Comment (bbrk24) [reply Dependiject/Factory.swift:81]: Additionally, locking for `get` vs `set`/`modify` works slightly differently in theory: Multiple threads can get the value at the same time; you only need to block a get if another thread is in the middle of setting. I haven't accounted for that in my current implementation -- the whole function takes the lock.

**Review by NicholasChase — APPROVED** [review]

File: Dependiject/Factory.swift (hunk 3 above)
Comment (wboyd600) [reply Dependiject/Factory.swift:81]: Yeah, I modified the parallel resolutions tests to modify the options with every iteration and ran it 100 times and it still passed so I think we're good

**Review by wboyd600 — APPROVED** [review]
